### ISSUE TITLE
Make number of jars visible from category screen

### ISSUE THREAD

**Issue by chryzrose** [mathuin/pyment#72]
Right now the user does not know how many jars are left of a given product until after they click on the product. Making the number of jars visible from the first screen would be helpful, perhaps under the SIP number or next to it.

**Comment by mathuin** [comment]
I'm not sure about this one.  I think it'll be too much text if every product has the count displayed, but I'll see what it looks like.  I definitely like the idea of having any product with less than 5-10 jars remaining having some kind of indicator like "Only 3 remaining!" in red or something.
