### ISSUE TITLE
Footer sometimes overlaps content

### ISSUE THREAD

**Issue by mythmon** [mathuin/pyment#94]
I'm not sure if this is the ocntent not reserving enough space (through things like overflow: hidden) or because the footer isn't pushing the content around enough, but either way, it looks like this: (I selected some stuff to clearly see the overlap into the footer):

![shot_25660](https://cloud.githubusercontent.com/assets/305049/7876944/665346ae-0588-11e5-861b-9cd8630f8e11.png)

**Comment by mathuin** [comment]
Yeah, #72 was my first pass at the new feature.

I have a few tweaks I want to make.  I need to make that space larger, as you noticed.  At the same time, I will probably limit the anchor to the mead name, not the batch identifier or the in-stock amount -- which will be in red when the in-stock amount is less than some parameter.
